# Generated by Django 5.1.4 on 2025-01-12 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNo', models.CharField(max_length=20)),
                ('effDate', models.DateField()),
                ('recData', models.DateField()),
                ('lessor', models.CharField(max_length=255)),
                ('lessee', models.CharField(max_length=255)),
                ('legal_desc', models.CharField(max_length=255)),
                ('term_in_years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('royalty', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MineralTract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('township', models.CharField(max_length=5)),
                ('range', models.CharField(max_length=5)),
                ('section', models.IntegerField()),
                ('gross', models.DecimalField(decimal_places=2, max_digits=5)),
                ('owner', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ogl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_tracts', to='myapp.ogl')),
            ],
        ),
    ]
