# Generated by Django 5.1.4 on 2025-01-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ogl_mineraltract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogl',
            old_name='recData',
            new_name='recDate',
        ),
        migrations.AddField(
            model_name='mineraltract',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ogl',
            name='legal_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ogl',
            name='royalty',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
